// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/booking_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	domain "github.com/butorovv/meeting-room-booking/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBookingRepositoryInterface is a mock of BookingRepositoryInterface interface.
type MockBookingRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryInterfaceMockRecorder
}

// MockBookingRepositoryInterfaceMockRecorder is the mock recorder for MockBookingRepositoryInterface.
type MockBookingRepositoryInterfaceMockRecorder struct {
	mock *MockBookingRepositoryInterface
}

// NewMockBookingRepositoryInterface creates a new mock instance.
func NewMockBookingRepositoryInterface(ctrl *gomock.Controller) *MockBookingRepositoryInterface {
	mock := &MockBookingRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepositoryInterface) EXPECT() *MockBookingRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBookingRepositoryInterface) Create(ctx context.Context, booking *domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBookingRepositoryInterfaceMockRecorder) Create(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookingRepositoryInterface)(nil).Create), ctx, booking)
}

// GetAll mocks base method.
func (m *MockBookingRepositoryInterface) GetAll(ctx context.Context, limit, offset int) ([]*domain.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockBookingRepositoryInterfaceMockRecorder) GetAll(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockBookingRepositoryInterface)(nil).GetAll), ctx, limit, offset)
}

// GetByID mocks base method.
func (m *MockBookingRepositoryInterface) GetByID(ctx context.Context, id string) (*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBookingRepositoryInterfaceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBookingRepositoryInterface)(nil).GetByID), ctx, id)
}

// GetBySlotID mocks base method.
func (m *MockBookingRepositoryInterface) GetBySlotID(ctx context.Context, slotID string) (*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlotID", ctx, slotID)
	ret0, _ := ret[0].(*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlotID indicates an expected call of GetBySlotID.
func (mr *MockBookingRepositoryInterfaceMockRecorder) GetBySlotID(ctx, slotID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlotID", reflect.TypeOf((*MockBookingRepositoryInterface)(nil).GetBySlotID), ctx, slotID)
}

// GetByUserID mocks base method.
func (m *MockBookingRepositoryInterface) GetByUserID(ctx context.Context, userID string) ([]*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockBookingRepositoryInterfaceMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockBookingRepositoryInterface)(nil).GetByUserID), ctx, userID)
}

// UpdateStatus mocks base method.
func (m *MockBookingRepositoryInterface) UpdateStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockBookingRepositoryInterfaceMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockBookingRepositoryInterface)(nil).UpdateStatus), ctx, id, status)
}
