// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/room_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/butorovv/meeting-room-booking/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockRoomRepositoryInterface is a mock of RoomRepositoryInterface interface.
type MockRoomRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRoomRepositoryInterfaceMockRecorder
}

// MockRoomRepositoryInterfaceMockRecorder is the mock recorder for MockRoomRepositoryInterface.
type MockRoomRepositoryInterfaceMockRecorder struct {
	mock *MockRoomRepositoryInterface
}

// NewMockRoomRepositoryInterface creates a new mock instance.
func NewMockRoomRepositoryInterface(ctrl *gomock.Controller) *MockRoomRepositoryInterface {
	mock := &MockRoomRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRoomRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomRepositoryInterface) EXPECT() *MockRoomRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomRepositoryInterface) Create(ctx context.Context, room *domain.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomRepositoryInterfaceMockRecorder) Create(ctx, room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomRepositoryInterface)(nil).Create), ctx, room)
}

// ExistsByID mocks base method.
func (m *MockRoomRepositoryInterface) ExistsByID(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByID", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByID indicates an expected call of ExistsByID.
func (mr *MockRoomRepositoryInterfaceMockRecorder) ExistsByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByID", reflect.TypeOf((*MockRoomRepositoryInterface)(nil).ExistsByID), ctx, id)
}

// List mocks base method.
func (m *MockRoomRepositoryInterface) List(ctx context.Context) ([]*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRoomRepositoryInterfaceMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoomRepositoryInterface)(nil).List), ctx)
}
