// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/schedule_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/butorovv/meeting-room-booking/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockScheduleRepositoryInterface is a mock of ScheduleRepositoryInterface interface.
type MockScheduleRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRepositoryInterfaceMockRecorder
}

// MockScheduleRepositoryInterfaceMockRecorder is the mock recorder for MockScheduleRepositoryInterface.
type MockScheduleRepositoryInterfaceMockRecorder struct {
	mock *MockScheduleRepositoryInterface
}

// NewMockScheduleRepositoryInterface creates a new mock instance.
func NewMockScheduleRepositoryInterface(ctrl *gomock.Controller) *MockScheduleRepositoryInterface {
	mock := &MockScheduleRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockScheduleRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRepositoryInterface) EXPECT() *MockScheduleRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScheduleRepositoryInterface) Create(ctx context.Context, schedule *domain.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScheduleRepositoryInterfaceMockRecorder) Create(ctx, schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheduleRepositoryInterface)(nil).Create), ctx, schedule)
}

// ExistsByRoomID mocks base method.
func (m *MockScheduleRepositoryInterface) ExistsByRoomID(ctx context.Context, roomID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByRoomID", ctx, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByRoomID indicates an expected call of ExistsByRoomID.
func (mr *MockScheduleRepositoryInterfaceMockRecorder) ExistsByRoomID(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByRoomID", reflect.TypeOf((*MockScheduleRepositoryInterface)(nil).ExistsByRoomID), ctx, roomID)
}

// GetByRoomID mocks base method.
func (m *MockScheduleRepositoryInterface) GetByRoomID(ctx context.Context, roomID string) (*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoomID", ctx, roomID)
	ret0, _ := ret[0].(*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoomID indicates an expected call of GetByRoomID.
func (mr *MockScheduleRepositoryInterfaceMockRecorder) GetByRoomID(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoomID", reflect.TypeOf((*MockScheduleRepositoryInterface)(nil).GetByRoomID), ctx, roomID)
}
