// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	domain "github.com/butorovv/meeting-room-booking/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockSlotRepositoryInterface is a mock of SlotRepositoryInterface interface.
type MockSlotRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSlotRepositoryInterfaceMockRecorder
}

// MockSlotRepositoryInterfaceMockRecorder is the mock recorder for MockSlotRepositoryInterface.
type MockSlotRepositoryInterfaceMockRecorder struct {
	mock *MockSlotRepositoryInterface
}

// NewMockSlotRepositoryInterface creates a new mock instance.
func NewMockSlotRepositoryInterface(ctrl *gomock.Controller) *MockSlotRepositoryInterface {
	mock := &MockSlotRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSlotRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlotRepositoryInterface) EXPECT() *MockSlotRepositoryInterfaceMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockSlotRepositoryInterface) BatchCreate(ctx context.Context, slots []*domain.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, slots)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockSlotRepositoryInterfaceMockRecorder) BatchCreate(ctx, slots interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockSlotRepositoryInterface)(nil).BatchCreate), ctx, slots)
}

// GetAvailableByRoomAndDate mocks base method.
func (m *MockSlotRepositoryInterface) GetAvailableByRoomAndDate(ctx context.Context, roomID, date string) ([]*domain.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableByRoomAndDate", ctx, roomID, date)
	ret0, _ := ret[0].([]*domain.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableByRoomAndDate indicates an expected call of GetAvailableByRoomAndDate.
func (mr *MockSlotRepositoryInterfaceMockRecorder) GetAvailableByRoomAndDate(ctx, roomID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableByRoomAndDate", reflect.TypeOf((*MockSlotRepositoryInterface)(nil).GetAvailableByRoomAndDate), ctx, roomID, date)
}

// GetByID mocks base method.
func (m *MockSlotRepositoryInterface) GetByID(ctx context.Context, id string) (*domain.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSlotRepositoryInterfaceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSlotRepositoryInterface)(nil).GetByID), ctx, id)
}
