// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/http/auth_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthUseCaseInterface is a mock of AuthUseCaseInterface interface.
type MockAuthUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUseCaseInterfaceMockRecorder
}

// MockAuthUseCaseInterfaceMockRecorder is the mock recorder for MockAuthUseCaseInterface.
type MockAuthUseCaseInterfaceMockRecorder struct {
	mock *MockAuthUseCaseInterface
}

// NewMockAuthUseCaseInterface creates a new mock instance.
func NewMockAuthUseCaseInterface(ctrl *gomock.Controller) *MockAuthUseCaseInterface {
	mock := &MockAuthUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockAuthUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUseCaseInterface) EXPECT() *MockAuthUseCaseInterfaceMockRecorder {
	return m.recorder
}

// DummyLogin mocks base method.
func (m *MockAuthUseCaseInterface) DummyLogin(ctx context.Context, role string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DummyLogin", ctx, role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DummyLogin indicates an expected call of DummyLogin.
func (mr *MockAuthUseCaseInterfaceMockRecorder) DummyLogin(ctx, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DummyLogin", reflect.TypeOf((*MockAuthUseCaseInterface)(nil).DummyLogin), ctx, role)
}
