// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/http/booking_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	domain "github.com/butorovv/meeting-room-booking/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBookingUseCaseInterface is a mock of BookingUseCaseInterface interface.
type MockBookingUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBookingUseCaseInterfaceMockRecorder
}

// MockBookingUseCaseInterfaceMockRecorder is the mock recorder for MockBookingUseCaseInterface.
type MockBookingUseCaseInterfaceMockRecorder struct {
	mock *MockBookingUseCaseInterface
}

// NewMockBookingUseCaseInterface creates a new mock instance.
func NewMockBookingUseCaseInterface(ctrl *gomock.Controller) *MockBookingUseCaseInterface {
	mock := &MockBookingUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockBookingUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingUseCaseInterface) EXPECT() *MockBookingUseCaseInterfaceMockRecorder {
	return m.recorder
}

// CancelBooking mocks base method.
func (m *MockBookingUseCaseInterface) CancelBooking(ctx context.Context, bookingID, userID string) (*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", ctx, bookingID, userID)
	ret0, _ := ret[0].(*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockBookingUseCaseInterfaceMockRecorder) CancelBooking(ctx, bookingID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockBookingUseCaseInterface)(nil).CancelBooking), ctx, bookingID, userID)
}

// CreateBooking mocks base method.
func (m *MockBookingUseCaseInterface) CreateBooking(ctx context.Context, userID, slotID string, conferenceLink *string) (*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, userID, slotID, conferenceLink)
	ret0, _ := ret[0].(*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockBookingUseCaseInterfaceMockRecorder) CreateBooking(ctx, userID, slotID, conferenceLink interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockBookingUseCaseInterface)(nil).CreateBooking), ctx, userID, slotID, conferenceLink)
}

// GetAllBookings mocks base method.
func (m *MockBookingUseCaseInterface) GetAllBookings(ctx context.Context, page, pageSize int) ([]*domain.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBookings", ctx, page, pageSize)
	ret0, _ := ret[0].([]*domain.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllBookings indicates an expected call of GetAllBookings.
func (mr *MockBookingUseCaseInterfaceMockRecorder) GetAllBookings(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBookings", reflect.TypeOf((*MockBookingUseCaseInterface)(nil).GetAllBookings), ctx, page, pageSize)
}

// GetUserBookings mocks base method.
func (m *MockBookingUseCaseInterface) GetUserBookings(ctx context.Context, userID string) ([]*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBookings", ctx, userID)
	ret0, _ := ret[0].([]*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBookings indicates an expected call of GetUserBookings.
func (mr *MockBookingUseCaseInterfaceMockRecorder) GetUserBookings(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBookings", reflect.TypeOf((*MockBookingUseCaseInterface)(nil).GetUserBookings), ctx, userID)
}
