// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/http/room_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/butorovv/meeting-room-booking/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockRoomUseCaseInterface is a mock of RoomUseCaseInterface interface.
type MockRoomUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRoomUseCaseInterfaceMockRecorder
}

// MockRoomUseCaseInterfaceMockRecorder is the mock recorder for MockRoomUseCaseInterface.
type MockRoomUseCaseInterfaceMockRecorder struct {
	mock *MockRoomUseCaseInterface
}

// NewMockRoomUseCaseInterface creates a new mock instance.
func NewMockRoomUseCaseInterface(ctrl *gomock.Controller) *MockRoomUseCaseInterface {
	mock := &MockRoomUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockRoomUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomUseCaseInterface) EXPECT() *MockRoomUseCaseInterfaceMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockRoomUseCaseInterface) CreateRoom(ctx context.Context, name string, description *string, capacity *int) (*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, name, description, capacity)
	ret0, _ := ret[0].(*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomUseCaseInterfaceMockRecorder) CreateRoom(ctx, name, description, capacity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomUseCaseInterface)(nil).CreateRoom), ctx, name, description, capacity)
}

// ListRooms mocks base method.
func (m *MockRoomUseCaseInterface) ListRooms(ctx context.Context) ([]*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx)
	ret0, _ := ret[0].([]*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockRoomUseCaseInterfaceMockRecorder) ListRooms(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockRoomUseCaseInterface)(nil).ListRooms), ctx)
}
