// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/http/schedule_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	domain "github.com/butorovv/meeting-room-booking/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockScheduleUseCaseInterface is a mock of ScheduleUseCaseInterface interface.
type MockScheduleUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleUseCaseInterfaceMockRecorder
}

// MockScheduleUseCaseInterfaceMockRecorder is the mock recorder for MockScheduleUseCaseInterface.
type MockScheduleUseCaseInterfaceMockRecorder struct {
	mock *MockScheduleUseCaseInterface
}

// NewMockScheduleUseCaseInterface creates a new mock instance.
func NewMockScheduleUseCaseInterface(ctrl *gomock.Controller) *MockScheduleUseCaseInterface {
	mock := &MockScheduleUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockScheduleUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleUseCaseInterface) EXPECT() *MockScheduleUseCaseInterfaceMockRecorder {
	return m.recorder
}

// CreateSchedule mocks base method.
func (m *MockScheduleUseCaseInterface) CreateSchedule(ctx context.Context, roomID string, daysOfWeek []int, startTime, endTime string) (*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, roomID, daysOfWeek, startTime, endTime)
	ret0, _ := ret[0].(*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockScheduleUseCaseInterfaceMockRecorder) CreateSchedule(ctx, roomID, daysOfWeek, startTime, endTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockScheduleUseCaseInterface)(nil).CreateSchedule), ctx, roomID, daysOfWeek, startTime, endTime)
}
