// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/http/slot_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	domain "github.com/butorovv/meeting-room-booking/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSlotUseCaseInterface is a mock of SlotUseCaseInterface interface.
type MockSlotUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSlotUseCaseInterfaceMockRecorder
}

// MockSlotUseCaseInterfaceMockRecorder is the mock recorder for MockSlotUseCaseInterface.
type MockSlotUseCaseInterfaceMockRecorder struct {
	mock *MockSlotUseCaseInterface
}

// NewMockSlotUseCaseInterface creates a new mock instance.
func NewMockSlotUseCaseInterface(ctrl *gomock.Controller) *MockSlotUseCaseInterface {
	mock := &MockSlotUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockSlotUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlotUseCaseInterface) EXPECT() *MockSlotUseCaseInterfaceMockRecorder {
	return m.recorder
}

// GetAvailableSlots mocks base method.
func (m *MockSlotUseCaseInterface) GetAvailableSlots(ctx context.Context, roomID, date string) ([]*domain.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableSlots", ctx, roomID, date)
	ret0, _ := ret[0].([]*domain.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableSlots indicates an expected call of GetAvailableSlots.
func (mr *MockSlotUseCaseInterfaceMockRecorder) GetAvailableSlots(ctx, roomID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableSlots", reflect.TypeOf((*MockSlotUseCaseInterface)(nil).GetAvailableSlots), ctx, roomID, date)
}
